name: flutter_contacts_example
description: Demonstrates how to use the flutter_contacts plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: 2.0.1

flutter:
  uses-material-design: true
