name: flutter_contacts_example
description: Demonstrates how to use the flutter_contacts plugin.
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
