name: flutter_contacts
description: Flutter plugin to read, create, update, delete and observe native contacts on Android and iOS, with group support, vCard support, and contact permission handling
version: 1.1.7+1
homepage: https://github.com/QuisApp/flutter_contacts

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.23.1

flutter:
  plugin:
    platforms:
      android:
        package: co.quis.flutter_contacts
        pluginClass: FlutterContactsPlugin
      ios:
        pluginClass: FlutterContactsPlugin
