name: flutter_contacts_example
description: Demonstrates how to use the flutter_contacts plugin.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2
  flutter_contacts:
    path: ../
  image_picker: ^1.0.2
  prompt_dialog: ^1.0.9

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
